import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'sudarshan',
      email: 'admin2@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'AdidasCore Shoes',
      slug: 'adidas-shoes',
      category: 'Shoes',
      image: '/images/ShoesImg.png',
      price: 100,
      countInStock: 2,
      brand: 'Adidas',
      rating: 5.0,
      numReviews: 50,
      description: 'high quality product',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Levi\'s Denim Jacket',
      slug: 'levis-denim-jacket',
      category: 'Jackets',
      image: '/images/levis-denim-jacket.jpeg',
      price: 150,
      countInStock: 7,
      brand: 'Levi\'s',
      rating: 4.2,
      numReviews: 18,
      description: 'high quality denim jacket',
    },
    {
      name: 'Tommy Hilfiger Polo Shirt',
      slug: 'tommy-hilfiger-polo-shirt',
      category: 'Shirts',
      image: '/images/Tommy-Hilfiger-Polo-Shirt.jpeg',
      price: 80,
      countInStock: 20,
      brand: 'Tommy Hilfiger',
      rating: 4.8,
      numReviews: 35,
      description: 'high quality polo shirt',
    },
    {
      name: 'Converse High Tops',
      slug: 'converse-high-tops',
      category: 'Shoes',
      image: '/images/converse-high-tops.jpeg',
      price: 70,
      countInStock: 12,
      brand: 'Converse',
      rating: 4.6,
      numReviews: 28,
      description: 'high top sneakers',
    },
    {
      name: 'Ray-Ban Aviator Sunglasses',
      slug: 'ray-ban-aviator-sunglasses',
      category: 'Accessories',
      image: '/images/ray-ban-aviator-sunglasses.jpeg',
      price: 200,
      countInStock: 3,
      brand: 'Ray-Ban',
      rating: 4.9,
      numReviews: 45,
      description: 'classic aviator sunglasses',
    },
    {
      name: 'Fossil Leather Wallet',
      slug: 'fossil-leather-wallet',
      category: 'Accessories',
      image: '/images/fossil-leather-wallet.jpeg',
      price: 50,
      countInStock: 18,
      brand: 'Fossil',
      rating: 4.4,
      numReviews: 22,
      description: 'genuine leather wallet',
    },
    {
      name: 'Columbia Waterproof Jacket',
      slug: 'columbia-waterproof-jacket',
      category: 'Jackets',
      image: "/images/columbia-waterproof-jacket.jpeg",
      price: 180,
      countInStock: 5,
      brand: 'Columbia',
      rating: 4.7,
      numReviews: 12,
      description: 'waterproof outdoor jacket',
    },
    {
      name: 'Under Armour Sports Leggings',
      slug: 'under-armour-sports-leggings',
      category: 'Leggings',
      image: '/images/under-armour-sports-leggings.jpeg',
      price: 45,
      countInStock: 9,
      brand: 'Under Armour',
      rating: 4.3,
      numReviews: 15,
      description: 'high performance sports leggings',
    },
    {
      name: 'New Balance Running Shoes',
      slug: 'new-balance-running-shoes',
      category: 'Shoes',
      image: '/images/new-balance-running-shoes.jpeg',
      price: 120,
      countInStock: 4,
      brand: 'New Balance',
      rating: 4.5,
      numReviews: 25,
      description: 'comfortable running shoes',
    },
    {
      name: 'Ralph Lauren Polo Shirt',
      slug: 'ralph-lauren-polo-shirt',
      category: 'Shirts',
      image: '/images/ralph-lauren-polo-shirt.jpeg',
      price: 95,
      countInStock: 14,
      brand: 'Ralph Lauren',
      rating: 4.6,
      numReviews: 30,
      description: 'classic polo shirt',
    },
    {
      name: 'Calvin Klein Briefs',
      slug: 'calvin-klein-briefs',
      category: 'Underwear',
      image: '/images/calvin-klein-briefs.jpeg',
      price: 30,
      countInStock: 25,
      brand: 'Calvin Klein',
      rating: 4.8,
      numReviews: 40,
      description: 'comfortable briefs',
    },
    {
      name: 'Gucci Leather Belt',
      slug: 'gucci-leather-belt',
      category: 'Accessories',
      image: '/images/gucci-leather-belt.jpeg',
      price: 250,
      countInStock: 6,
      brand: 'Gucci',
      rating: 4.9,
      numReviews: 55,
      description: 'luxurious leather belt',
    },
  ],
};

export default data;
